### ISSUE TITLE
Add inport/export function for workflow input

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#223]
![Image](https://github.com/user-attachments/assets/0ec8a556-06e9-4bce-89cb-704ad16052c9)

1. export: export json format (json file), include all info relate input defined
2. inport: import json file (show all inout)

**Comment by thucaothidieu** [comment]
**BUGS:**
1. UI: `Import Workflow Input` should be aligned


![Image](https://github.com/user-attachments/assets/0a686d51-899d-4019-b679-179a4887cc0c)


2. Do not display name of request after importing json file


https://github.com/user-attachments/assets/e2ce38fe-55b0-435e-8be9-b3390e780c84
