### ISSUE TITLE
option set color for request template when create new one

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#224]
be https://github.com/ncc-erp/ncc-erp-workflow-w2/pull/141/files
fe https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/pull/147/files

1. Review if can not use ==> close
2. Add field: 'settings: json string' in table WorkflowCustomInputDefinitions
3. Save color to settings field { color: '#fff' }
4. UI - split define workflow input to 2 parts
the first part for settings field (add Color and color picker for choosing color), the second for add new fileds

![Image](https://github.com/user-attachments/assets/4da64f59-bc37-472c-a9ed-beb0ddc4a1f8)

**Comment by thucaothidieu** [comment]
**BUG:**

AR: The color of Settings field is changed to white after adding new field
ER: The color of Setting field should remain after adding new field


https://github.com/user-attachments/assets/f1ea5456-8f41-46b6-b10f-ce81da60f261
