### ISSUE TITLE
Add setting page for admin

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#228]
![Image](https://github.com/user-attachments/assets/507a59e6-9b9a-4ee6-91b1-effed1bfb19c)

Add new menu (Settings) inlude some settings
1. GDVP config
Add/Edit Office (Name, Code, Email GDVP)
3. IT group
Add/Remove danh sach IT emails
5. HR group
Add/Remove danh sach HR emails
6. CEO
Add/Remove danh sach CEO emails

This config we be using when sending or assign task in workflow

**Comment by thiendangncc** [comment]
Estimation: 9:00 11/09 (tạo PR)

**Comment by NguyenHuuMinhHuy1504** [comment]
[Evidence video link part 1](https://drive.google.com/file/d/1zj_UZvsiuB6VntifybR4yRzi7fKnXYD2/view?usp=sharing)
[Evidence video link part 2](https://drive.google.com/file/d/1wNPGqEEBWDyyPkrGHRwHXjrjKzbLiQKg/view?usp=sharing)
