### ISSUE TITLE
Add filter by role for User Management

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#236]
recheck pr
be https://github.com/ncc-erp/ncc-erp-workflow-w2/pull/140
fe https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/pull/146

**Comment by thiendangncc** [comment]
in charge: http://w2-dev2.nccsoft.vn/administration/user-management

**Comment by NguyenHuuMinhHuy1504** [comment]
[Evidence](https://drive.google.com/file/d/1XIoxmgMxn9CyFk3KpfzGJYP4g7h3as7I/view?usp=sharing)
