### ISSUE TITLE
Show line break for content when using textarea

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#243]
![Image](https://github.com/user-attachments/assets/e9391f3e-f115-4c21-9c93-928f837fb71d)
![Image](https://github.com/user-attachments/assets/7c10a6db-02c0-466a-9410-fa22fdfa7f08)

Notes: Apply cho cả trang task + request + tất cả các loại request có input textarea

**Comment by hongdiem-nguyen** [comment]
[evidence]
https://drive.google.com/file/d/1Tv7DEv7-lZmU0JGnP-PcaWxj0tpSrmpb/view?usp=sharing
