### ISSUE TITLE
[BUG] Request's status is not updated in realtime when clicking on it to view details after approved/rejected

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#244]
STEPS:
1. Staff has sent a Change office request 
2. PM / Current HoO / Destination HoO approves / rejects the request
3. PM / Current HoO / Destination HoO click on the approved/rejected requests to view its details
4. Observe

EXPECTED RESULTS: 
Request's status should be updated in realtime in the details

ACTUAL RESULTS:
Request's status is not updated in realtime in the details 
- Approve and Reject button are still displayed
- Status is still Pending

https://github.com/user-attachments/assets/abc6ca0b-e21d-41c6-8d47-895bee80d11a

![Image](https://github.com/user-attachments/assets/4e1162ed-8553-49ba-9b30-4e7dd0183eb5)

**Comment by NguyenHuuMinhHuy1504** [comment]
[Evidence video link](https://drive.google.com/file/d/10KktvuWuNkAg8mpKYkssd19dFLiLppyd/view?usp=sharing)
