### ISSUE TITLE
consitence hover row state of table

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#246]
follow requests table (when user hover to row of table)
![Image](https://github.com/user-attachments/assets/3d3a4d02-ee67-4b69-bcee-62e9f19c8f52)

apply for tasks table and users table
Notes: 
both light and dark mode
Apply for common table

**Comment by hongdiem-nguyen** [comment]
[evidence]
https://drive.google.com/file/d/1RLwbWpVZyPEpPUJys_k7zy9l5-Q8fom-/view?usp=sharing
