### ISSUE TITLE
Add a new rewust "Resignation Request"

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#255]
nhân viên request xin nghỉ việc
    input: 
        + mong muốn ngày làm việc cuối cùng
        + lý do:
-> gửi đến pm:
    approve: input
        + ngày làm việc cuối cùng
        + note:
    reject: 
        + lý do:
Gửi mail GDVP (k cần approve)
pm approve -> gửi đến hpm
    approve: 
        + ngày làm việc cuối cùng
        + note
    reject: 
        + lý do
hpm approve -> gửi đến HR
    approve
        + ngày làm việc cuối cùng
        + note:
    reject:
        + lý do
HR approve -> gửi đến IT
Note: Gửi cùng lúc cho pm, hpm, hr, GDVP. 
sau khi pm, hpm, hr approve hết thì gửi IT
-------------
create request
gửi PM, HPM, HR, GDVP (gửi mail)
tất cả approve ==> approve ==> gửi mail IT

**Comment by thiendangncc** [comment]
@NguyenHuuMinhHuy1504 comment + estimation

**Comment by NguyenHuuMinhHuy1504** [comment]
> [@NguyenHuuMinhHuy1504](https://github.com/NguyenHuuMinhHuy1504) comment + estimation
**task:**

- thêm HPM setting
- thêm 2 field là last woking day và note vào theo dạng dynamic form
- check permission khi approve/reject vì hiện tại các user khác ngoài thien.dang thì bị báo no permission
- self test

**Estimation:**

- 18h - 20/9
