### ISSUE TITLE
Write e2e [ Probationary Confirmation Request]

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#261]

**Comment by hongdiem-nguyen** [comment]
1. **As pm, I want to be received a Probationary Confirmation Request**
S1: I can see the pending request in my tasks
S2: I can approve request successfully by title, strength points and weekness points
S3: I can reject request by reason
2. **As gdvpdn, I want to be received a Probationary Confirmation Request**
S1:  I can see the pending request in my tasks
S2: I can approve request successfully by title, strength points and weekness points
S3: I can reject request with the reasons
3. **As ceo, I want to be received a Probationary Confirmation Request after **pm and gdvpdn** approved**
S1: I can see the pending request in my tasks
S2: I can approve request
S2: I can reject request with the reasons
4. **As user, I want to see a Probationary Confirmation Request after CEO approved**
S1: I can see the a success request on my request page

-------------
ISSUES:
1. ![Image](https://github.com/user-attachments/assets/19d18f1c-0534-49e2-8b51-4dea8b541899)
For CEO Reviews, it has sendMailAndAssign, but in the template dont assign task for ceo
![Image](https://github.com/user-attachments/assets/09fc8ca5-a6f7-427f-bc31-2594e79f9b2c)
2. When pm and gdvp approve the task
That request is shown in approve tasks section but in workflow => show reject flow
**evidence:** https://drive.google.com/file/d/1A39cQzjaQohmhSJF6tji71RW-TuQI66K/view?usp=sharing
