### ISSUE TITLE
add publish/unpublish for template manager

### ISSUE THREAD

**Issue by thiendangncc** [ncc-erp/ncc-erp-workflow-w2-ui#272]
Solution:

Create an API in the backend to receive the workflow ID and the publish status (true or false) and update in the database. In the frontend, develop the UI components that allow users to toggle the publish status and call the API to send the updated data.

Estimation: 10 AM, October 17.

![Image](https://github.com/user-attachments/assets/bfaff95a-7ce1-469b-b771-926d1d2b48d3)

**Comment by huyendangthithanh** [comment]
**Testing passed on Dev**
https://github.com/user-attachments/assets/6d7920c0-63ff-44dd-8066-a6d8073034b0
